apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gcr.io/cs436-project-460307/my-backend
          ports:
            - containerPort: 3001
          env:
            - name: DB_HOST
              value: "10.186.0.20"
            - name: DB_USER
              value: "appuser"
            - name: DB_PASSWORD
              value: "E1m1c1kege."
            - name: DB_NAME
              value: "movie_booking_db"
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
